
window.PFHCalendar=(function(){
 const PEOPLE={MOM:"#8b5cf6",DAD:"#8b929a",MIGUEL:"#f4bd32",FONSI:"#3187cf",PRINCESS:"#eb64a4",FAMILY:"#48a86d"};
 let events=[],view="week",anchor=new Date(),enabled=new Set(Object.keys(PEOPLE));
 const $=s=>document.querySelector(s), ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
 const parse=s=>{let [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
 const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
 function monday(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
 function fromGoogle(g){let x=g.extendedProperties?.shared||{};if(x.pfhType==="chore")return null;let all=!!g.start?.date;return {id:g.id,title:g.summary||"(Untitled)",person:x.pfhPerson||"FAMILY",allDay:all,date:all?g.start.date:g.start.dateTime.slice(0,10),start:all?"":g.start.dateTime.slice(11,16),end:all?"":g.end.dateTime.slice(11,16),notes:g.description||""}}
 function loadFromItems(items){events=(items||[]).map(fromGoogle).filter(Boolean);render()} async function sync(){if(!PFHGoogle.isConnected()){events=[];render();return}loadFromItems(await PFHGoogle.list())}
 function filters(){let box=$("#filters");box.innerHTML=Object.entries(PEOPLE).map(([p,c])=>`<button class="filter ${enabled.has(p)?"on":""}" data-filter="${p}" style="background:${c}33;color:${p==="MIGUEL"?"#6b5100":c}">${p}</button>`).join("");box.onclick=e=>{let b=e.target.closest("[data-filter]");if(!b)return;enabled.has(b.dataset.filter)?enabled.delete(b.dataset.filter):enabled.add(b.dataset.filter);filters();render()}}
 function eventHtml(e){let c=PEOPLE[e.person]||PEOPLE.FAMILY, initial=e.person==="FAMILY"?"F":e.person[0];return `<div class="event" data-event="${e.id}" style="background:${c}22;border-left-color:${c}"><strong><span class="avatar" style="background:${c}">${initial}</span>${esc(e.title)}</strong><span>${e.allDay?"All day":e.start+"–"+e.end} · ${e.person}</span></div>`}
 function renderWeek(){let s=monday(anchor),days=[];for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i);days.push(d)}$("#calendarTitle").textContent=`${days[0].toLocaleDateString("en-US",{month:"long",day:"numeric"})} – ${days[6].toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}`;let today=ymd(new Date());$("#calendarGrid").className="weekGrid";$("#calendarGrid").innerHTML=days.map(d=>{let ds=ymd(d),es=events.filter(e=>e.date===ds&&enabled.has(e.person));return `<div class="day ${ds===today?"today":""}"><div class="dayHead">${d.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}<b>${d.getDate()}</b></div>${es.map(eventHtml).join("")}</div>`}).join("")}
 function renderMonth(){let y=anchor.getFullYear(),m=anchor.getMonth(),first=new Date(y,m,1),grid=monday(first);$("#calendarTitle").textContent=anchor.toLocaleDateString("en-US",{month:"long",year:"numeric"});$("#calendarGrid").className="monthGrid";let h="";for(let i=0;i<42;i++){let d=new Date(grid);d.setDate(grid.getDate()+i);let ds=ymd(d),es=events.filter(e=>e.date===ds&&enabled.has(e.person));h+=`<div class="monthDay" style="${d.getMonth()!==m?"opacity:.45":""}"><div class="n">${d.getDate()}</div>${es.slice(0,3).map(eventHtml).join("")}</div>`}$("#calendarGrid").innerHTML=h}
 function renderSchedule(){let list=events.filter(e=>enabled.has(e.person)&&parse(e.date)>=new Date(new Date().setHours(0,0,0,0))).slice(0,60);$("#calendarTitle").textContent="Upcoming Schedule";$("#calendarGrid").className="schedule";$("#calendarGrid").innerHTML=list.length?list.map(e=>`<div class="scheduleRow" data-event="${e.id}"><b>${parse(e.date).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</b><div>${eventHtml(e)}</div></div>`).join(""):`<div class="empty">No upcoming events.</div>`}
 function summaries(){let t=ymd(new Date()), tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let a=events.filter(e=>e.date===t&&enabled.has(e.person)),b=events.filter(e=>parse(e.date)>=new Date(tomorrow.setHours(0,0,0,0))&&enabled.has(e.person)).slice(0,6);$("#todayList").innerHTML=a.length?a.map(e=>`<div class="summaryRow">${eventHtml(e)}</div>`).join(""):`<div class="empty">No events today.</div>`;$("#comingList").innerHTML=b.length?b.map(e=>`<div class="summaryRow"><b>${parse(e.date).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</b>${eventHtml(e)}</div>`).join(""):`<div class="empty">Nothing coming up.</div>`}
 function render(){if(view==="week")renderWeek();else if(view==="month")renderMonth();else renderSchedule();summaries()}
 function bodyFromForm(fd){let date=fd.get("date"),all=fd.get("allDay")==="on",person=fd.get("person"),b={summary:fd.get("title"),description:fd.get("notes")||"",extendedProperties:{shared:{pfhPerson:person}}};if(all){let end=parse(date);end.setDate(end.getDate()+1);b.start={date};b.end={date:ymd(end)}}else{let tz=Intl.DateTimeFormat().resolvedOptions().timeZone;b.start={dateTime:`${date}T${fd.get("start")}:00`,timeZone:tz};b.end={dateTime:`${date}T${fd.get("end")}:00`,timeZone:tz}}return b}
 function openEditor(e=null){let modal=$("#modal"),form=$("#editorForm");$("#modalTitle").textContent=e?"Edit Event":"Add Event";let today=ymd(new Date());form.innerHTML=`<div class="formGrid"><div class="field full"><label>Event title</label><input name="title" required value="${esc(e?.title||"")}"></div><div class="field"><label>Person</label><select name="person">${Object.keys(PEOPLE).map(p=>`<option ${e?.person===p?"selected":""}>${p}</option>`).join("")}</select></div><div class="field"><label>Date</label><input type="date" name="date" required value="${e?.date||today}"></div><div class="field full"><label><input type="checkbox" name="allDay" ${e?.allDay?"checked":""}> All day</label></div><div class="field"><label>Start</label><input type="time" name="start" value="${e?.start||"09:00"}"></div><div class="field"><label>End</label><input type="time" name="end" value="${e?.end||"10:00"}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(e?.notes||"")}</textarea></div><div class="formActions">${e?'<button type="button" id="deleteEvent" class="danger">Delete</button>':""}<button type="button" class="ghost" id="cancelEdit">Cancel</button><button class="primary">Save Event</button></div></div>`;modal.classList.remove("hidden");let st=form.elements.start,en=form.elements.end;st.addEventListener("change",()=>{let [h,m]=st.value.split(":").map(Number);en.value=`${String((h+1)%24).padStart(2,"0")}:${String(m).padStart(2,"0")}`});$("#cancelEdit").onclick=close;form.onsubmit=async ev=>{ev.preventDefault();try{let b=bodyFromForm(new FormData(form)),path="/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events"+(e?"/"+encodeURIComponent(e.id):"");await PFHGoogle.api(path,{method:e?"PUT":"POST",body:JSON.stringify(b)});close();await sync()}catch(x){alert(x.message)}};if(e)$("#deleteEvent").onclick=async()=>{if(!confirm("Delete this event?"))return;try{await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(e.id),{method:"DELETE"});close();await sync()}catch(x){alert(x.message)}}}
 function close(){$("#modal").classList.add("hidden")}
 function init(){filters();document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));render()});$("#addEventBtn").onclick=()=>openEditor();$("#todayBtn").onclick=()=>{anchor=new Date();render()};$("#prevBtn").onclick=()=>{view==="month"?anchor.setMonth(anchor.getMonth()-1):anchor.setDate(anchor.getDate()-7);render()};$("#nextBtn").onclick=()=>{view==="month"?anchor.setMonth(anchor.getMonth()+1):anchor.setDate(anchor.getDate()+7);render()};$("#calendarGrid").onclick=e=>{let n=e.target.closest("[data-event]");if(n){let ev=events.find(x=>x.id===n.dataset.event);if(ev)openEditor(ev)}};$("#modalClose").onclick=close;render()}
 return {init,sync,render,loadFromItems,ymd,parse,PEOPLE,esc};
})();
