
window.PFHChores=(function(){
 let chores=[];const $=s=>document.querySelector(s),{ymd,parse,PEOPLE,esc}=PFHCalendar;
 function fromGoogle(g){let x=g.extendedProperties?.shared||{};if(x.pfhType!=="chore")return null;return{id:g.id,title:g.summary||"Chore",person:x.pfhPerson||"FAMILY",done:x.pfhDone==="true",repeat:x.pfhRepeat||"none",date:g.start?.date||g.start?.dateTime?.slice(0,10),notes:g.description||""}}
 async function sync(items=null){if(!PFHGoogle.isConnected()){chores=[];render();return}let all=items||await PFHGoogle.list();chores=all.map(fromGoogle).filter(Boolean);render()}
 function render(){let open=chores.filter(c=>!c.done).length,done=chores.filter(c=>c.done).length;$("#choreStats").innerHTML=`<div class="stat">${open} open</div><div class="stat">${done} done</div>`;let list=[...chores].sort((a,b)=>a.date.localeCompare(b.date));$("#choreList").innerHTML=list.length?list.map(c=>{let col=PEOPLE[c.person]||PEOPLE.FAMILY;return `<div class="chore ${c.done?"done":""}" style="border-left-color:${col}"><div class="choreTop"><button class="check" data-check="${c.id}">${c.done?"✓":""}</button><div><div class="choreName">${esc(c.title)}</div><div class="meta">${c.person} · ${parse(c.date).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})} · ${c.repeat==="none"?"One time":c.repeat[0].toUpperCase()+c.repeat.slice(1)}</div>${c.notes?`<div class="meta">${esc(c.notes)}</div>`:""}</div></div><div class="choreActions"><button data-edit="${c.id}">Edit</button></div></div>`}).join(""):`<div class="empty">No chores yet. Add the first one.</div>`}
 function openEditor(c=null){let form=$("#editorForm");$("#modalTitle").textContent=c?"Edit Chore":"Add Chore";form.innerHTML=`<div class="formGrid"><div class="field full"><label>Chore name</label><input name="title" required value="${esc(c?.title||"")}"></div><div class="field"><label>Assigned to</label><select name="person">${Object.keys(PEOPLE).map(p=>`<option ${c?.person===p?"selected":""}>${p}</option>`).join("")}</select></div><div class="field"><label>Due date</label><input type="date" name="date" required value="${c?.date||ymd(new Date())}"></div><div class="field"><label>Repeat</label><select name="repeat">${[["none","One time"],["daily","Daily"],["weekly","Weekly"],["monthly","Monthly"]].map(([v,l])=>`<option value="${v}" ${c?.repeat===v?"selected":""}>${l}</option>`).join("")}</select></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(c?.notes||"")}</textarea></div><div class="formActions">${c?'<button type="button" id="deleteChore" class="danger">Delete</button>':""}<button type="button" id="cancelChore" class="ghost">Cancel</button><button class="primary">Save Chore</button></div></div>`;$("#modal").classList.remove("hidden");$("#cancelChore").onclick=()=>$("#modal").classList.add("hidden");form.onsubmit=async e=>{e.preventDefault();let fd=new FormData(form),date=fd.get("date"),end=parse(date);end.setDate(end.getDate()+1),body={summary:fd.get("title"),description:fd.get("notes")||"",transparency:"transparent",start:{date},end:{date:ymd(end)},extendedProperties:{shared:{pfhType:"chore",pfhPerson:fd.get("person"),pfhDone:String(c?.done||false),pfhRepeat:fd.get("repeat")}}};try{let path="/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events"+(c?"/"+encodeURIComponent(c.id):"");await PFHGoogle.api(path,{method:c?"PUT":"POST",body:JSON.stringify(body)});$("#modal").classList.add("hidden");await window.PFHApp.syncAll()}catch(x){alert(x.message)}};if(c)$("#deleteChore").onclick=async()=>{if(!confirm("Delete this chore?"))return;try{await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(c.id),{method:"DELETE"});$("#modal").classList.add("hidden");await window.PFHApp.syncAll()}catch(x){alert(x.message)}}}
 async function toggle(id){let c=chores.find(x=>x.id===id);if(!c)return;try{if(!c.done&&c.repeat!=="none"){let d=parse(c.date);if(c.repeat==="daily")d.setDate(d.getDate()+1);if(c.repeat==="weekly")d.setDate(d.getDate()+7);if(c.repeat==="monthly")d.setMonth(d.getMonth()+1);let date=ymd(d),end=parse(date);end.setDate(end.getDate()+1);await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({start:{date},end:{date:ymd(end)},extendedProperties:{shared:{pfhType:"chore",pfhPerson:c.person,pfhDone:"false",pfhRepeat:c.repeat}}})})}else{await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({extendedProperties:{shared:{pfhType:"chore",pfhPerson:c.person,pfhDone:String(!c.done),pfhRepeat:c.repeat}}})})}await window.PFHApp.syncAll()}catch(x){alert(x.message)}}
 function init(){$("#addChoreBtn").onclick=()=>openEditor();$("#choreList").onclick=e=>{let b=e.target.closest("[data-check]");if(b)return toggle(b.dataset.check);let ed=e.target.closest("[data-edit]");if(ed){let c=chores.find(x=>x.id===ed.dataset.edit);if(c)openEditor(c)}};render()}
 return {init,sync,render};
})();
