window.PFHLists=(function(){
let lists=[],activeId=null;const $=s=>document.querySelector(s),{ymd,esc}=PFHCalendar;
function parseItems(x){try{let a=JSON.parse(x||"[]");return Array.isArray(a)?a:[]}catch{return[]}}
function fromGoogle(g){let x=g.extendedProperties?.shared||{};if(x.pfhType!=="list")return null;return{id:String(g.id),title:g.summary||"List",items:parseItems(g.description)}}
function loadFromItems(items){lists=(items||[]).map(fromGoogle).filter(Boolean);if(activeId&&!lists.some(l=>l.id===activeId))activeId=null;if(!activeId&&lists.length)activeId=lists[0].id;render()}
async function sync(items=null){if(!PFHGoogle.isConnected()){lists=[];activeId=null;render();return}loadFromItems(items||await PFHGoogle.list())}
function active(){return lists.find(l=>l.id===activeId)}
function render(){let a=active();$("#listTabs").innerHTML=lists.length?lists.map(l=>`<button class="listTab ${l.id===activeId?"active":""}" data-list="${esc(l.id)}"><span>☷</span><b>${esc(l.title)}</b><small>${l.items.filter(i=>!i.done).length}</small></button>`).join(""):`<div class="empty">No lists yet.</div>`;$("#listEmpty").classList.toggle("hidden",!!a);$("#listContent").classList.toggle("hidden",!a);if(!a)return;$("#activeListTitle").textContent=a.title;$("#listCount").textContent=`${a.items.filter(i=>!i.done).length} remaining · ${a.items.length} total`;$("#listItems").innerHTML=a.items.length?a.items.map((i,n)=>`<div class="listItem ${i.done?"checked":""}"><button class="itemCheck" data-toggle="${n}">${i.done?"✓":""}</button><span>${esc(i.text)}</span><button class="itemDelete" data-delete="${n}">×</button></div>`).join(""):`<div class="empty">This list is empty.</div>`;$("#clearCheckedBtn").style.display=a.items.some(i=>i.done)?"inline-block":"none"}
async function save(l){let d=new Date(),e=new Date(d);e.setDate(e.getDate()+1);let body={summary:l.title,description:JSON.stringify(l.items),transparency:"transparent",start:{date:ymd(d)},end:{date:ymd(e)},extendedProperties:{shared:{pfhType:"list"}}};await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(l.id),{method:"PUT",body:JSON.stringify(body)});await PFHApp.syncAll()}
async function create(){let title=prompt("List name:","Grocery");if(!title?.trim())return;let d=new Date(),e=new Date(d);e.setDate(e.getDate()+1);let body={summary:title.trim(),description:"[]",transparency:"transparent",start:{date:ymd(d)},end:{date:ymd(e)},extendedProperties:{shared:{pfhType:"list"}}};try{let g=await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events",{method:"POST",body:JSON.stringify(body)});activeId=String(g.id);await PFHApp.syncAll()}catch(x){alert(x.message)}}
async function mutate(fn){let a=active();if(!a)return;let c={...a,items:a.items.map(i=>({...i}))};fn(c.items);try{await save(c)}catch(x){alert(x.message)}}
function init(){$("#addListBtn").onclick=create;$("#listTabs").onclick=e=>{let b=e.target.closest("[data-list]");if(b){activeId=b.dataset.list;render()}};$("#renameListBtn").onclick=async()=>{let a=active(),t=a&&prompt("Rename list:",a.title);if(t?.trim()){try{await save({...a,title:t.trim()})}catch(x){alert(x.message)}}};$("#deleteListBtn").onclick=async()=>{let a=active();if(!a||!confirm(`Delete "${a.title}"?`))return;try{await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(a.id),{method:"DELETE"});activeId=null;await PFHApp.syncAll()}catch(x){alert(x.message)}};$("#addItemForm").onsubmit=e=>{e.preventDefault();let i=$("#newItemText"),t=i.value.trim();if(t){i.value="";mutate(a=>a.push({text:t,done:false}))}};$("#listItems").onclick=e=>{let t=e.target.closest("[data-toggle]");if(t)return mutate(a=>{a[+t.dataset.toggle].done=!a[+t.dataset.toggle].done});let d=e.target.closest("[data-delete]");if(d)mutate(a=>a.splice(+d.dataset.delete,1))};$("#clearCheckedBtn").onclick=()=>mutate(a=>{for(let i=a.length-1;i>=0;i--)if(a[i].done)a.splice(i,1)});render()}
return{init,sync,render,loadFromItems};})();