window.PFHLists=(function(){
let lists=[],activeId=null;const $=s=>document.querySelector(s),{esc}=PFHCalendar;
async function sync(){lists=await PFHFirebase.all("lists");if(activeId&&!lists.some(l=>l.id===activeId))activeId=null;if(!activeId&&lists.length)activeId=lists[0].id;render()}
function active(){return lists.find(l=>l.id===activeId)}
function render(){let a=active();$("#listTabs").innerHTML=lists.length?lists.map(l=>`<button class="listTab ${l.id===activeId?"active":""}" data-list="${esc(l.id)}"><span>☷</span><b>${esc(l.title)}</b><small>${(l.items||[]).filter(i=>!i.done).length}</small></button>`).join(""):`<div class="empty">No lists yet.</div>`;$("#listEmpty").classList.toggle("hidden",!!a);$("#listContent").classList.toggle("hidden",!a);if(!a)return;a.items=Array.isArray(a.items)?a.items:[];$("#activeListTitle").textContent=a.title;$("#listCount").textContent=`${a.items.filter(i=>!i.done).length} remaining · ${a.items.length} total`;$("#listItems").innerHTML=a.items.length?a.items.map((i,n)=>`<div class="listItem ${i.done?"checked":""}"><button class="itemCheck" data-toggle="${n}">${i.done?"✓":""}</button><span>${esc(i.text)}</span><button class="itemDelete" data-delete="${n}">×</button></div>`).join(""):`<div class="empty">This list is empty.</div>`;$("#clearCheckedBtn").style.display=a.items.some(i=>i.done)?"inline-block":"none"}
async function save(l){await PFHFirebase.set("lists",l.id,{title:l.title,items:l.items||[]});await sync()}
async function create(){let title=prompt("List name:","Grocery");if(!title?.trim())return;try{let id=await PFHFirebase.set("lists",null,{title:title.trim(),items:[]});activeId=id;await sync()}catch(x){alert(x.message)}}
async function mutate(fn){let a=active();if(!a)return;let c={...a,items:(a.items||[]).map(i=>({...i}))};fn(c.items);try{await save(c)}catch(x){alert(x.message)}}
async function addItemsToNamedList(name,texts){let l=lists.find(x=>x.title.toLowerCase()===String(name).toLowerCase());if(!l)throw Error(`Create a list named "${name}" first.`);let c={...l,items:(l.items||[]).map(i=>({...i}))};for(const t of texts){let v=String(t||"").trim();if(v)c.items.push({text:v,done:false})}await save(c)}
function init(){$("#addListBtn").onclick=create;$("#listTabs").onclick=e=>{let b=e.target.closest("[data-list]");if(b){activeId=b.dataset.list;render()}};$("#renameListBtn").onclick=async()=>{let a=active(),t=a&&prompt("Rename list:",a.title);if(t?.trim()){try{await save({...a,title:t.trim()})}catch(x){alert(x.message)}}};$("#deleteListBtn").onclick=async()=>{let a=active();if(!a||!confirm(`Delete "${a.title}"?`))return;try{await PFHFirebase.remove("lists",a.id);activeId=null;await sync()}catch(x){alert(x.message)}};$("#addItemForm").onsubmit=e=>{e.preventDefault();let i=$("#newItemText"),t=i.value.trim();if(t){i.value="";mutate(a=>a.push({text:t,done:false}))}};$("#listItems").onclick=e=>{let t=e.target.closest("[data-toggle]");if(t)return mutate(a=>{a[+t.dataset.toggle].done=!a[+t.dataset.toggle].done});let d=e.target.closest("[data-delete]");if(d)mutate(a=>a.splice(+d.dataset.delete,1))};$("#clearCheckedBtn").onclick=()=>mutate(a=>{for(let i=a.length-1;i>=0;i--)if(a[i].done)a.splice(i,1)});render()}
return{init,sync,render,addItemsToNamedList};})();
