window.PFHMeals=(function(){
let meals=[],anchor=new Date();const $=s=>document.querySelector(s),{ymd,parse,esc}=PFHCalendar,TYPES=["Breakfast","Lunch","Dinner"];
function monday(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function fromGoogle(g){const x=g.extendedProperties?.shared||{};if(x.pfhType!=="meal")return null;return{id:String(g.id),title:g.summary||"Meal",date:g.start?.date||g.start?.dateTime?.slice(0,10),type:x.pfhMealType||"Dinner",notes:g.description||"",recipe:x.pfhRecipe||""}}
function loadFromItems(items){meals=(items||[]).map(fromGoogle).filter(Boolean);render()}
function days(){let m=monday(anchor),a=[];for(let i=0;i<7;i++){let d=new Date(m);d.setDate(m.getDate()+i);a.push(d)}return a}
function render(){const ds=days(),today=ymd(new Date());$("#mealWeekTitle").textContent=`${ds[0].toLocaleDateString("en-US",{month:"short",day:"numeric"})} – ${ds[6].toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}`;$("#mealGrid").innerHTML=ds.map(d=>{let date=ymd(d);return `<section class="mealDay ${date===today?"today":""}"><div class="mealDayHead"><span>${d.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}</span><b>${d.getDate()}</b></div>${TYPES.map(type=>{let list=meals.filter(m=>m.date===date&&m.type===type);return `<div class="mealSlot ${type==="Dinner"?"dinner":""}"><div class="mealSlotLabel">${type}</div>${list.length?list.map(m=>`<button class="mealCard" data-meal="${esc(m.id)}"><strong>${esc(m.title)}</strong>${m.notes?`<small>${esc(m.notes)}</small>`:""}</button>`).join(""):`<button class="mealEmpty" data-new-meal="${date}|${type}">+ Add</button>`}</div>`}).join("")}</section>`}).join("")}
function openEditor(m=null,date=null,type="Dinner"){const f=$("#editorForm");$("#modalTitle").textContent=m?"Edit Meal":"Add Meal";f.innerHTML=`<div class="formGrid"><div class="field full"><label>Meal</label><input name="title" required value="${esc(m?.title||"")}"></div><div class="field"><label>Date</label><input type="date" name="date" required value="${m?.date||date||ymd(new Date())}"></div><div class="field"><label>Meal type</label><select name="type">${TYPES.map(t=>`<option ${((m?.type||type)===t)?"selected":""}>${t}</option>`).join("")}</select></div><div class="field full"><label>Notes</label><textarea name="notes" placeholder="Sides, prep notes, who's cooking…">${esc(m?.notes||"")}</textarea></div><div class="field full"><label>Recipe / link (optional)</label><input type="url" name="recipe" placeholder="https://…" value="${esc(m?.recipe||"")}"></div><div class="formActions">${m?'<button type="button" id="deleteMeal" class="danger">Delete</button>':""}<button type="button" id="cancelMeal" class="ghost">Cancel</button><button class="primary">Save Meal</button></div></div>`;$("#modal").classList.remove("hidden");$("#cancelMeal").onclick=()=>$("#modal").classList.add("hidden");f.onsubmit=async e=>{e.preventDefault();let fd=new FormData(f),date=fd.get("date"),end=parse(date);end.setDate(end.getDate()+1);let body={summary:fd.get("title"),description:fd.get("notes")||"",transparency:"transparent",start:{date},end:{date:ymd(end)},extendedProperties:{shared:{pfhType:"meal",pfhMealType:fd.get("type"),pfhRecipe:fd.get("recipe")||""}}};try{let path="/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events"+(m?"/"+encodeURIComponent(m.id):"");await PFHGoogle.api(path,{method:m?"PUT":"POST",body:JSON.stringify(body)});$("#modal").classList.add("hidden");await PFHApp.syncAll()}catch(x){alert(x.message)}};if(m)$("#deleteMeal").onclick=async()=>{if(!confirm("Delete this meal?"))return;try{await PFHGoogle.api("/calendars/"+encodeURIComponent(PFHGoogle.CALENDAR_ID)+"/events/"+encodeURIComponent(m.id),{method:"DELETE"});$("#modal").classList.add("hidden");await PFHApp.syncAll()}catch(x){alert(x.message)}}}
function init(){$("#addMealBtn").onclick=()=>openEditor();$("#mealPrevBtn").onclick=()=>{anchor.setDate(anchor.getDate()-7);render()};$("#mealNextBtn").onclick=()=>{anchor.setDate(anchor.getDate()+7);render()};$("#mealTodayBtn").onclick=()=>{anchor=new Date();render()};$("#mealGrid").onclick=e=>{let n=e.target.closest("[data-new-meal]");if(n){let [d,t]=n.dataset.newMeal.split("|");openEditor(null,d,t);return}let b=e.target.closest("[data-meal]");if(b){let m=meals.find(x=>x.id===b.dataset.meal);if(m)openEditor(m)}};render()}
return{init,render,loadFromItems};})();